device: cuda:0
experiment_name: upp_with_401_flip_rotate_brightness
checkpoints_folder: leanai_core_yolo/segm_filter/checkpoints
results_folder: leanai_core_yolo/segm_filter/results
num_classes: 3
kfold:
  train_kfold: False
  num_folds: 5
model:
  name: UnetPlusPlus
  args: { in_channels: 1, classes: 3, decoder_use_batchnorm: False }
loss:
  name: SoftCrossEntropyLoss
  args: {}
metrics:
  name: JaccardIndex
  args:
    task: multiclass
    num_classes: 3
train_ds:
  root: /home/lean-ai-yaniv/projects/for_segmentation/results/train
test_ds:
  root: /home/lean-ai-yaniv/projects/for_segmentation/results/test

train_transform:
  - name: RandomBrightnessContrast
    args:
      brightness_limit: 0.3
      contrast_limit: 0.3
      p: 0.5
      
  - name: RandomRotate90
    args:
      p: 0.5
  - name: Flip
    args:
      p: 0.5

  - name: Normalize
    args:
      mean: 0.449
      std: 0.226
      #mean: 0
      #std: 1

  - name: ToTensorV2
    args:
      transpose_mask: False

test_transform:
  - name: Normalize
    args:
      mean: 0.449
      std: 0.226
      #mean: 0
      #std: 1
  - name: ToTensorV2
    args:
      transpose_mask: False

train_dataloader:
  batch_size: 2
  num_workers: 8
  shuffle: True

test_dataloader:
  batch_size: 1
  num_workers: 2
  shuffle: False

optimizer:
  learning_rate: 0.0001
  weight_decay: 0.00001

train:
  init:
    amp_mode: amp
    scaler: True
  run:
    max_epochs: 10

draw:
  dataset: /home/lean-ai-yaniv/projects/for_segmentation/results
  model: /home/lean-ai-yaniv/projects/leanai_yolov7/leanai_core_yolo/segm_filter/checkpoints/model_ckpt_11900.pt
  batch_size: 100
  num_workers: 2
